Repository remote-develop-study/js-clean-todo, pull requests merged in 2021-12, with the labels that each got.

#9 [STEP 02] TodoItem 수정하기
  js/index.js
Labels: 🚀 🚀 step2

#7 [STEP 02] TodoItem 수정, Todo 갯수 표시 + STEP 01 리팩터링
  index.html
  index.js
  src/components/App.js
  src/components/Component.js
  src/components/TodoCountContainer.js
  src/components/TodoForm.js
  src/components/TodoList.js
  src/css/styles.css
  src/utils/domCreator.js
  src/utils/getMaxNumber.js
  src/utils/selector.js
Labels: 🚀 🚀 step2, 🙋‍♂️🙋‍♀️ review wanted

#8 [STEP 02] 수정, 개수 표시 추가 및 리팩터링
  README.md
  index.html
  src/components/TodoItem.js
  src/components/TodoList.js
  src/index.js
  src/utils/domUtils.js
  src/utils/queryUtils.js
  src/utils/todoUtils.js
Labels: 🚀 🚀 step2, 🙋‍♂️🙋‍♀️ review wanted

#10 [STEP 02] TodoItem 수정하기
  .eslintrc.js
  README.md
  src/app.js
  src/components/TodoList.js
  src/constant/dom.js
  src/handler/todoItem.js
  src/index.js
  src/model/Model.js
  src/template/template.js
  src/utils/validator.js
Labels: 🚀 🚀 step2, 🙋‍♂️🙋‍♀️ review wanted

#13 [STEP 03] TodoItem 상태관리
  index.html
  js/index.js
  js/utils/dom.js
Labels: 🚀🚀🚀 step3, 🙋‍♂️🙋‍♀️ review wanted
